# Generated by Django 5.1.3 on 2025-10-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conductor_apellidos_conductor_nombres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='camera_source',
            field=models.CharField(blank=True, help_text='Índice de cámara (0) o URL RTSP/HTTP', max_length=200, null=True, verbose_name='Fuente de cámara'),
        ),
    ]
