# Generated by Django 5.1.3 on 2025-10-22 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conductor_camera_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critical_events', to='core.conductor')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critical_events', to='core.vehiculo')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
