# Generated by Django 5.1.3 on 2025-10-30 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_criticalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='licencia_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento de licencia'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='documento',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', message='El número de documento debe contener sólo dígitos.')]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', message='El teléfono debe contener sólo dígitos.')], verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='La placa debe tener exactamente 6 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='servicio',
            field=models.CharField(choices=[('particular', 'Particular'), ('publico', 'Público')], max_length=20),
        ),
    ]
