# Generated by Django 6.0.3 on 2026-04-09 21:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conductor_licencia_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}\\d{3}$', message='La placa debe tener el formato AAA111 (3 letras y 3 dígitos).')]),
        ),
        migrations.CreateModel(
            name='MobileTelemetrySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre_conductor', models.CharField(blank=True, max_length=150)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('fatigue_index', models.IntegerField(default=100)),
                ('estado', models.CharField(default='normal', max_length=40)),
                ('face_detected', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='mobile_local', max_length=40)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_snapshots', to='core.conductor')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
