# Generated by Django 6.0.3 on 2026-04-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vehiculo_placa_mobiletelemetrysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletelemetrysnapshot',
            name='document_issue_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
